name: creating an AWS RDS postgres database and creating table into it using terraform

on:
    push:
        branches:
            - main

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
            
          - name: install terraform
            uses: hashicorp/setup-terraform@v3
            with:
                terraform_version: 1.11.0

          - name: create a ssh file in github runner
            run: |
              echo "${{ secrets.OPENSSH_PRIVATE_KEY }}" > terraform.pem
              chmod 600 terraform.pem

          - name: set SSH key path to terraform
            run: echo "TF_VAR_ssh_private_key_path=$(pwd)/terraform.pem" >> $GITHUB_ENV
  
          - name: terraform init
            run: terraform init

          - name: terraform apply
            run: terraform apply -auto-approve
            env:
                TF_VAR_OPENSSH_PRIVATE_KEY: ${{ secrets.OPENSSH_PRIVATE_KEY }}
                TF_VAR_OPENSSH_PUBLIC_KEY: ${{ secrets.OPENSSH_PUBLIC_KEY }}
                TF_VAR_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}